### ISSUE TITLE
Any game crashes when trying to run

### ISSUE THREAD

**Issue by Pyroglyph** [ddfreyne/inari#5]
This happens for every game in Inari. After installing the shards and building a game, launching it just prints this error to the terminal:
```
Unhandled exception: Cannot convert comp 0 (Exception)
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
```

OS: Ubuntu 16.04
Crystal version: 0.27.0

**Comment by denisdefreyne** [comment]
Hey Connor,

How are you building and running the game? This works for me:

```
% make
…

% ./dist/release/cli/forest
```

The error that you get is from glove, and it happens in [texture.cr](https://github.com/ddfreyne/glove/blob/68bda0a17d62a2ad30d9b51f58d4667b2ccd28cd/src/texture.cr#L18), presumably when an image fails to be loaded. This might be because of filesystem permissions, or because the current working directory is not the right one.

The games in Inari all change their working directory to be the directory that contains the executable ([source](https://github.com/ddfreyne/inari/blob/e25ab342f3b3148e805ce72bf6345010f241d2c0/forest/src/inari/inari.cr#L58-L60)). It might be the case that this is not working as intended.

I can’t reproduce the problem on my machine. Would you be willing to give a shot at investigating why the images can’t be loaded?

**Comment by Pyroglyph** [comment]
Whoops! I guess I'm too used to working with .NET since I was trying to run `./build/release/forest` and I didn't notice the `dist` directory! Facepalm.
